"""
Django settings for django_redis project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7lx(9g*v2i150y@q_fij*-oq+$8@xon!63s(kf^3yzwr3p0bdc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'celeryapp',
    
    'gmailapi_backend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_redis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_redis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_FROM = 'tungnguyen.antc@gmail.com'
EMAIL_BACKEND = 'gmailapi_backend.mail.GmailBackend'
GMAIL_API_CLIENT_ID = '355923939124-uj5skph5kjs9irs43qibost6oksjrl1h.apps.googleusercontent.com'
GMAIL_API_CLIENT_SECRET = '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'
# GMAIL_API_REFRESH_TOKEN = '1//0gGpQmakvzwdWCgYIARAAGBASNwF-L9IrRAsffyU4gyjwKV1b3m4JxE0yVQ_47lTJ0kNWf1FZZdI126elMEJd3mMBHtG50GZ7lJQ'
GMAIL_API_REFRESH_TOKEN = '1//0gw5TkJXyfq-tCgYIARAAGBASNwF-L9IrG3ch7mcLOHW7TPg3fAYPnK6pXP4fUBM1BKayTDyyA7ECABbWtqmmBYVmDd_lhqPDtrw'


CELERY_REDIS_USERNAME='djangocelery'
CELERY_REDIS_PASSWORD='ThuanThanh@5079'
CELERY_BROKER_URL = f'redis://{CELERY_REDIS_USERNAME}:{CELERY_REDIS_PASSWORD}@redis-18465.c265.us-east-1-2.ec2.cloud.redislabs.com:18465'
CELERY_BROKER_TRANSPORT = 'redis'
CELERY_RESULT_BACKEND = f'redis://{CELERY_REDIS_USERNAME}:{CELERY_REDIS_PASSWORD}@redis-18465.c265.us-east-1-2.ec2.cloud.redislabs.com:18465'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


CELERY_IMPORTS = ("celeryapp.tasks", )
CELERY_BEAT_SCHEDULE = {
    "send_email": {
        
        "task": "celeryapp.tasks.send_email",
        
        "schedule": timedelta(minutes=1),

    },
}